# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasks.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttn_close = QtWidgets.QPushButton(self.centralwidget)
        self.buttn_close.setMinimumSize(QtCore.QSize(75, 23))
        self.buttn_close.setObjectName("buttn_close")
        self.verticalLayout_2.addWidget(self.buttn_close)
        self.change_theme = QtWidgets.QPushButton(self.centralwidget)
        self.change_theme.setObjectName("change_theme")
        self.verticalLayout_2.addWidget(self.change_theme)
        self.buttn_save = QtWidgets.QPushButton(self.centralwidget)
        self.buttn_save.setMinimumSize(QtCore.QSize(75, 23))
        self.buttn_save.setObjectName("buttn_save")
        self.verticalLayout_2.addWidget(self.buttn_save)
        self.bttn_open_file = QtWidgets.QPushButton(self.centralwidget)
        self.bttn_open_file.setObjectName("bttn_open_file")
        self.verticalLayout_2.addWidget(self.bttn_open_file)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.buttn_close.setText(_translate("MainWindow", "закрыть"))
        self.change_theme.setText(_translate("MainWindow", "под окружение"))
        self.buttn_save.setText(_translate("MainWindow", "обновить"))
        self.bttn_open_file.setText(_translate("MainWindow", "открыть"))
