# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.close_btn = QtWidgets.QPushButton(self.widget)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_4.addWidget(self.close_btn)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stop = QtWidgets.QPushButton(self.widget)
        self.stop.setObjectName("stop")
        self.horizontalLayout_5.addWidget(self.stop)
        self.pause = QtWidgets.QPushButton(self.widget)
        self.pause.setObjectName("pause")
        self.horizontalLayout_5.addWidget(self.pause)
        self.start = QtWidgets.QPushButton(self.widget)
        self.start.setDefault(False)
        self.start.setObjectName("start")
        self.horizontalLayout_5.addWidget(self.start)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setTextFormat(QtCore.Qt.AutoText)
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setWordWrap(False)
        self.time_label.setObjectName("time_label")
        self.verticalLayout_4.addWidget(self.time_label)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hour = QtWidgets.QSpinBox(self.widget_2)
        self.hour.setObjectName("hour")
        self.horizontalLayout_3.addWidget(self.hour)
        self.min = QtWidgets.QSpinBox(self.widget_2)
        self.min.setObjectName("min")
        self.horizontalLayout_3.addWidget(self.min)
        self.second = QtWidgets.QSpinBox(self.widget_2)
        self.second.setObjectName("second")
        self.horizontalLayout_3.addWidget(self.second)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.setup = QtWidgets.QPushButton(self.widget_3)
        self.setup.setObjectName("setup")
        self.verticalLayout_2.addWidget(self.setup)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Таймер"))
        self.close_btn.setText(_translate("MainWindow", "close"))
        self.pushButton.setText(_translate("MainWindow", "соответсвовать теме"))
        self.stop.setText(_translate("MainWindow", "stop"))
        self.pause.setText(_translate("MainWindow", "pause"))
        self.start.setText(_translate("MainWindow", "start"))
        self.time_label.setText(_translate("MainWindow", "00:00:00"))
        self.setup.setText(_translate("MainWindow", "установить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
